#!/bin/sh

# Merge xresources before i3 starts
xrdb ~/.config/x11/xresources

# Set english layout for better tilde placement etc
setxkbmap -layout gb

# Get pulse working
# start-pulseaudio-x11

# qtile is kept as default
session=${1:-qtile}

case $session in
	qtile								) exec qtile start;;
	# No known session, try to run it as command
	* 								) exec $1;;
esac
