#!/bin/sh

# Merge xresources before i3 starts
xrdb ~/.config/x11/xresources

# Set english layout for better tilde placement etc
setxkbmap -layout gb

# Get pulse working
start-pulseaudio-x11

# Set wallpaper
fehbg

# Start picom
picom -b

# Start redshift
redshift &

# Start bluetooth babes
blueman-applet &

# dwm is kept as default
session=${1:-dwm}

case $session in
  qtile							) exec qtile start;;
  awesome           ) exec awesome;;
  dwm               ) exec dwm;;
	# No known session, try to run it as command
	* 								) exec $1;;
esac
