-- /home/jedn/Documents/jedotfiles/xdg_config/nvim/colors/jn_dracula.lua
-- Dracula | Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)
-- Generated by jn-theme-generate — do not edit directly

vim.g.colors_name = 'jn_dracula'

require('mini.base16').setup({
  palette = {
    base00 = '#282936',
    base01 = '#3a3c4e',
    base02 = '#4d4f68',
    base03 = '#626483',
    base04 = '#62d6e8',
    base05 = '#e9e9f4',
    base06 = '#f1f2f8',
    base07 = '#f7f7fb',
    base08 = '#ea51b2',
    base09 = '#b45bcf',
    base0A = '#00f769',
    base0B = '#ebff87',
    base0C = '#a1efe4',
    base0D = '#62d6e8',
    base0E = '#b45bcf',
    base0F = '#00f769',
  },
  use_cterm = true,
  plugins = {
    default = false,
    ['nvim-mini/mini.nvim'] = true,
  },
})
