-- /home/jedn/Documents/jedotfiles/xdg_config/nvim/colors/jn_monokai.lua
-- Monokai | Wimer Hazenberg (http://www.monokai.nl)
-- Generated by jn-theme-generate — do not edit directly

vim.g.colors_name = 'jn_monokai'

require('mini.base16').setup({
  palette = {
    base00 = '#272822',
    base01 = '#383830',
    base02 = '#49483e',
    base03 = '#75715e',
    base04 = '#a59f85',
    base05 = '#f8f8f2',
    base06 = '#f5f4f1',
    base07 = '#f9f8f5',
    base08 = '#f92672',
    base09 = '#fd971f',
    base0A = '#f4bf75',
    base0B = '#a6e22e',
    base0C = '#a1efe4',
    base0D = '#66d9ef',
    base0E = '#ae81ff',
    base0F = '#cc6633',
  },
  use_cterm = true,
  plugins = {
    default = false,
    ['nvim-mini/mini.nvim'] = true,
  },
})
