-- /home/jedn/Documents/jedotfiles/xdg_config/nvim/colors/jn_oxocarbon-light.lua
-- Oxocarbon Light | shaunsingh/IBM (https://github.com/nyoom-engineering/base16-oxocarbon)
-- Generated by jn-theme-generate — do not edit directly

vim.g.colors_name = 'jn_oxocarbon-light'

require('mini.base16').setup({
  palette = {
    base00 = '#f2f4f8',
    base01 = '#dde1e6',
    base02 = '#525252',
    base03 = '#161616',
    base04 = '#262626',
    base05 = '#393939',
    base06 = '#525252',
    base07 = '#08bdba',
    base08 = '#ff7eb6',
    base09 = '#ee5396',
    base0A = '#FF6F00',
    base0B = '#0f62fe',
    base0C = '#673AB7',
    base0D = '#42be65',
    base0E = '#be95ff',
    base0F = '#37474F',
  },
  use_cterm = true,
  plugins = {
    default = false,
    ['nvim-mini/mini.nvim'] = true,
  },
})
