-- /home/jedn/Documents/jedotfiles/xdg_config/nvim/colors/jn_solarized-dark.lua
-- Solarized Dark | Ethan Schoonover (modified by aramisgithub)
-- Generated by jn-theme-generate — do not edit directly

vim.g.colors_name = 'jn_solarized-dark'

require('mini.base16').setup({
  palette = {
    base00 = '#002b36',
    base01 = '#073642',
    base02 = '#586e75',
    base03 = '#657b83',
    base04 = '#839496',
    base05 = '#93a1a1',
    base06 = '#eee8d5',
    base07 = '#fdf6e3',
    base08 = '#dc322f',
    base09 = '#cb4b16',
    base0A = '#b58900',
    base0B = '#859900',
    base0C = '#2aa198',
    base0D = '#268bd2',
    base0E = '#6c71c4',
    base0F = '#d33682',
  },
  use_cterm = true,
  plugins = {
    default = false,
    ['nvim-mini/mini.nvim'] = true,
  },
})
