# prompt config

add_newline = true

[line_break]
disabled = false

[gcloud]
disabled = false
# format = "[$symbol$account(@$project)]($style) "
detect_env_vars = ["GOOGLE_CLOUD_PROJECT"]

[ruby]
detect_files = [".ruby-version", "Gemfile", "Gemfile.lock", ".rbenv-version"]
detect_variables = []

[c]
style = "green"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 4
truncation_symbol = "…/"
