#!/bin/bash

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 4
berryc title_height       24
berryc edge_gap           0 54 0 0

# Set decoration colors
berryc focus_color         575279
berryc unfocus_color       575279
berryc inner_focus_color   1f1d2e
berryc inner_unfocus_color 1f1d2e
berryc text_focus_color    e0def4
berryc text_unfocus_color  e0def4

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "monospace-14"
